### ISSUE TITLE
The HDF5 file can't be recognized by caffe

### ISSUE THREAD

**Issue by beilusikeni** [jmoudrik/deep-go-wrap#1]
Hi, there

i made the hdf5 dataset, and tried to train it with caffe, but caffe can't read the file at all, so what i can  do next? thanks.

**Comment by jmoudrik** [comment]
Hello,

could you please provide some more details, such as error logs, etc?

The format is normal hdf5 and by googling (caffe hdf5) I get plenty of
information. Of course, the data layout (e.g. input shapes, etc), need to
be specified in your model.

Regards,
Josef

**Comment by beilusikeni** [comment]
Hi, Josef

i have solved the problem with your good instructions. You really did a great job.

thanks and best regards,
beilu
